
import turtle
window = turtle.Screen()
turtle.shape('turtle')
turtle.shapesize(1)
turtle.bgcolor("#1d0af0")
turtle.color("#d5ed1c")
turtle.pensize(3)
turtle.speed(2)
turtle.fillcolor("#f5161d")
turtle.begin_fill()
turtle.forward(70)
turtle.right(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(35)
turtle.end_fill()
turtle.right(180)
turtle.forward(35)
turtle.left(90)
turtle.forward(35)
turtle.fillcolor("#e6f516")
turtle.begin_fill()
turtle.circle(-25)
turtle.end_fill()
