
print("Hello! My name is John!")
name = input("Enter your name:")
age = input("Enter your age:")
number = input("Enter your phone number:")
print(f"Hello, {name}! Your are {age} years old. Your phone number is:{number}")
print("Java")
print("Kotlin")
print("Csharp")
print("C++")
print("C")
print("Swift")
print("PHP")
print("Ruby")
print("JavaScript")
print("TypeScript")
